### ISSUE TITLE
请问如何关掉这个软件实现的功能

### ISSUE THREAD

**Issue by MrKyomoto** [SpaceTimee/Sheas-Cealer#13]
不好意思,我对这些内容确实是不懂

开了一次之后,那些网站确实可以正常访问了,但是之后关掉软件也照样可以访问,我尝试删除Cealer-Host json文件,但是仍然可以访问,我不知道其中的原理,我现在不知道如何关掉

**Comment by MrKyomoto** [comment]
实在不好意思,我重启了一下电脑就发现恢复正常了,浪费您的时间了

**Comment by SpaceTimee** [comment]
关掉浏览器就解除伪造了

**Comment by MrKyomoto** [comment]
@SpaceTimee 感觉可能是有点小问题,我第一次打开软件之后,先手动关掉软件,再关掉浏览器,然后再次打开浏览器,仍然没有解除伪造,我不明白其中的原理(也许是虽然我关掉了chrome的网页,但是chrome的后台进程还在,所以其实没有完全关掉?)

**Comment by SpaceTimee** [comment]
应该是的，可能会有后台残留

关浏览器的时候不要直接关窗口。通过右上角三个点打开菜单，然后点 退出 来关闭浏览器应该就不会有后台残留了
