### ISSUE TITLE
win10 点击没有反应，不知道为啥

### ISSUE THREAD

**Issue by hotsmile** [SpaceTimee/Sheas-Cealer#15]
win10 点击没有反应，不知道为啥

**Comment by SpaceTimee** [comment]
装了 .Net8 运行时吗

**Comment by SpaceTimee** [comment]
你的系统版本是 Win10 ltsc 吗，Sheas Cealer 新版在 Win10 ltsc 和 Win7 上似乎运行不了，我研究一下解决办法，你可以试试 1.1.0 打不打的开

![Image_233638751051289.png](https://github.com/user-attachments/assets/a9e1e7db-3b93-4277-8cad-e4c4437a9e58)

**Comment by SpaceTimee** [comment]
1.1.4 中已修复这个问题
https://github.com/SpaceTimee/Sheas-Cealer/releases/tag/1.1.4
