### ISSUE TITLE
youtube无法看视频

### ISSUE THREAD

**Issue by liujianbo2024** [SpaceTimee/Sheas-Cealer#17]
![屏幕截图 2024-11-25 124338](https://github.com/user-attachments/assets/c42773e4-b0cc-4dec-bec9-123aaf2b3c47)

**Comment by SpaceTimee** [comment]
参考 [Special Cealing Instruction](https://github.com/SpaceTimee/Cealing-Host/wiki/Special%E2%80%90Cealing%E2%80%90Instruction#%E5%A6%82%E4%BD%95%E4%BC%AA%E9%80%A0-youtube-%E8%A7%86%E9%A2%91%E8%B5%84%E6%BA%90-googlevideocom)
