### ISSUE TITLE
合法性其实是个玄学问题

### ISSUE THREAD

**Issue by SeaHOH** [SpaceTimee/Sheas-Cealer#2]
当这个软件得到广泛传播后，它一定会被定性为非法，有理有据那种。

此帐号似乎暴露了相当多的个人信息，建议清除，否则最好不要公开此仓库。我也有写代理工具，但是个人信息是真的不敢暴露。如果你真的想继续，建议开小号。

**Comment by SpaceTimee** [comment]
Sheas Cealer 其实并不是代理工具，目前大陆的现行法律没有直接规定不得提供绕过国家防火墙的软件，一般具有以下特征中至少一条的翻墙软件才会被定义为违法：

1. 提供自行建立其他信道进行国际联网 (这也是大多数依赖代理的翻墙软件违法的原因)
2. 靠翻墙软件大量盈利，可能违反非法经营罪等
3. 对网络设备进行攻击或干扰，如西厢1
4. 教唆有损于国家的行为或参与某些国家禁止的活动，如自由门
5. 盗取个人信息

Sheas Cealer 并不违反上述任意一条，甚至不会对数据进行特殊加密 (可阅读代码考证)，目前 (没有相关的新法规出台之前) Sheas Cealer 可以保证在大陆完全合法，所以不必担心，如果情况有所变动，我也会采取其他措施来应对的

**Comment by SeaHOH** [comment]
法律条文要怎么用怎么解释，不是我们平头百姓说了算，而且不一定非要牵扯到你所提到的这些。言尽于此，望慎重考虑。

**Comment by Pantyhose-X** [comment]
你好 @SpaceTimee @SeaHOH 软件关于 我建议 你的联系方式改用[session](https://github.com/oxen-io/session-desktop),   创建一个[brave浏览器](https://github.com/brave/brave-browser)钱包，方便向你捐款

**Comment by SpaceTimee** [comment]
> 你好 @SpaceTimee @SeaHOH 软件关于 我建议 你的联系方式改用[session](https://github.com/oxen-io/session-desktop), 创建一个[brave浏览器](https://github.com/brave/brave-browser)钱包，方便向你捐款

好的，感谢建议，我会考虑添加更保密的联系方式。关于捐款的事，目前项目没有支出，不需要获得捐款支持

**Comment by Xihihhh** [comment]
[确定](https://www.gov.cn/yaowen/liebiao/202408/content_6971464.htm)了。

> 审议通过《加快完善海河流域防洪体系实施方案》和[《网络数据安全管理条例（草案）》](https://www.cac.gov.cn/2021-11/14/c_1638501991577898.htm)，讨论《中华人民共和国海商法（修订草案）》。

> 第四十一条 国家建立数据跨境安全网关，对来源于中华人民共和国境外、法律和行政法规禁止发布或者传输的信息予以阻断传播。
>
> **任何个人和组织不得提供用于穿透、绕过数据跨境安全网关的程序、工具、线路等，不得为穿透、绕过数据跨境安全网关提供互联网接入、服务器托管、技术支持、传播推广、支付结算、应用下载等服务。**
>
> 境内用户访问境内网络的，其流量不得被路由至境外。

**Comment by SpaceTimee** [comment]
> https://www.gov.cn/yaowen/liebiao/202408/content_6971464.htm
> 
> > 审议通过《加快完善海河流域防洪体系实施方案》和 **《网络数据安全管理条例（草案）》**，讨论《中华人民共和国海商法（修订草案）》。
> 
> 这个草案是不是[《征求意见稿》](https://www.cac.gov.cn/2021-11/14/c_1638501991577898.htm)还未知。

我最担心还是要来了，但也请不必担心，当法案正式实施的时候，Sheas Cealer 会做出相应的改变来应对

**Comment by SpaceTimee** [comment]
> https://www.gov.cn/zhengce/content/202409/content_6977766.htm
> 
> > 第三十九条　国家采取措施，防范、处置网络数据跨境安全风险和威胁。任何个人、组织不得提供**专门**用于破坏、避开技术措施的程序、工具等；明知他人从事破坏、避开技术措施等活动的，不得为其提供技术支持或者帮助。
> 
> 不需要改变，这个工具并不是专门用于破坏、避开技术的。

这个新规昨天我们群里也讨论了: [https://t.me/PixCealerChat/1379](https://t.me/PixCealerChat/1379)
