### ISSUE TITLE
使用Edge启动出现Error：拒绝访问

### ISSUE THREAD

**Issue by yuzdoge** [SpaceTimee/Sheas-Cealer#21]
使用Edge启动伪造，弹出
Error：拒绝访问
提示框框

**Comment by yuzdoge** [comment]
Windows11
Edge版本：131.0.2903.70

**Comment by SpaceTimee** [comment]
试试以管理员身份运行呢

**Comment by yuzdoge** [comment]
> 试试以管理员身份运行呢

也不行

**Comment by elarbor** [comment]
![image](https://github.com/user-attachments/assets/2a91b3a5-56eb-48a0-810e-d519a96c0903)

**Comment by SpaceTimee** [comment]
> ![image](https://github.com/user-attachments/assets/2a91b3a5-56eb-48a0-810e-d519a96c0903)
> 

你看一下这个文件有没有被设置成只读

**Comment by SpaceTimee** [comment]
1.1.4 现在在打开文件失败后会自动尝试重新以管理员权限打开，试试你遇到的问题在 [1.1.4] (https://github.com/SpaceTimee/Sheas-Cealer/releases/tag/1.1.4) 中是否修复

**Comment by yuzdoge** [comment]
> 1.1.4 现在在打开文件失败后会自动尝试重新以管理员权限打开，试试你遇到的问题在 [1.1.4](https://github.com/SpaceTimee/Sheas-Cealer/releases/tag/1.1.4) 中是否修复

1.1.4修复了该问题。（但有另外一个小问题，我需要先打开edge后再使用sheas-cealer，使用启动伪造；如果我直接使用sheas-cealer启动伪造，不会打开edge）

**Comment by XuTeLi888** [comment]
> 1.1.4 现在在打开文件失败后会自动尝试重新以管理员权限打开，试试你遇到的问题在 [1.1.4](https://github.com/SpaceTimee/Sheas-Cealer/releases/tag/1.1.4) 中是否修复

你好，我现在1.1.4版本启动伪造也会提示拒绝访问，该如何解决？（已使用管理员权限启动）

**Comment by XuTeLi888** [comment]
> > 1.1.4 现在在打开文件失败后会自动尝试重新以管理员权限打开，试试你遇到的问题在 [1.1.4](https://github.com/SpaceTimee/Sheas-Cealer/releases/tag/1.1.4) 中是否修复
> 
> 1.1.4修复了该问题。（但有另外一个小问题，我需要先打开edge后再使用sheas-cealer，使用启动伪造;如果我直接使用sheas-cealer启动伪造，不会打开edge）

![Image](https://github.com/user-attachments/assets/8aa93317-587d-40ba-9676-2602039d748e)
