### ISSUE TITLE
打开youtobe网站，视频一直缓冲，看不了

### ISSUE THREAD

**Issue by zhiyuanhao100** [SpaceTimee/Sheas-Cealer#22]
打开youtobe网站，视频一直缓冲，看不了，等很长时间还是这样。github、谷歌都能打开。

**Comment by SpaceTimee** [comment]
Duplicate of https://github.com/SpaceTimee/Sheas-Cealer/issues/17

**Comment by misividkoukou** [comment]
> Duplicate of #17
我想提醒的是，即使是打开了全局代理也会出现视频无法播放的问题，F12观察所有的传输都是失效的，最多比以前在拖动进度条时可以加载那一刻的画面与字幕
