### ISSUE TITLE
请求把窗口移动速度调慢一点

### ISSUE THREAD

**Issue by shadow-Mas-code** [SpaceTimee/Sheas-Cealer#25]
应用里那个小游戏难度太高了，能不能下调一下

**Comment by SpaceTimee** [comment]
TG 群内的投票结果是更多人希望保持现在这样需要特殊手段才能通关的难度

**Comment by 15114611836** [comment]
> 应用里那个小游戏难度太高了，能不能下调一下

本人有点好奇，那小游戏除了彩蛋有什么其他用吗？如果想关闭的话，在任务管理器就能关

**Comment by SpaceTimee** [comment]
> 本人有点好奇，那小游戏除了彩蛋有什么其他用吗？如果想关闭的话，在任务管理器就能关

之前 Sheas Cealer 还不支持 "将 null 作为伪造规则第二参数来去除整个 server name" 的时候，可以通过触发小游戏 (不用打通关) 然后再点击启动全局伪造这种方式去除所有伪造规则匹配到的流量的 server name (这是伪造 twitch nicovideo 等网站所必须的)，新版本加了 null 作为第二参数这个功能之后小游戏就是纯彩蛋没什么其他用了
