### ISSUE TITLE
🐛 : [bug] 无法启动

### ISSUE THREAD

**Issue by Pantyhose-X** [SpaceTimee/Sheas-Cealer#3]
bug  启动Sheas Cealer后 关闭浏览器  再也不能点击Sheas Cealer启动打开浏览器了，重启PC后。 Sheas Cealer也无法启动浏览器

**Comment by SpaceTimee** [comment]
我在 Windows 11 环境下尝试了 Edge 和 Chrome，没有能成功复现这个问题，你试试右键以管理员身份运行 Sheas Cealer 能不能解决

**Comment by Pantyhose-X** [comment]
> 我在 Windows 11 环境下尝试了 Edge 和 Chrome，没有能成功复现这个问题，你试试右键以管理员身份运行 Sheas Cealer 能不能解决

我不知道是什么引起的，我使用[Dism++](https://github.com/Chuyu-Team/Dism-Multi-language) 清理垃圾后，现在正常运行了

**Comment by SpaceTimee** [comment]
是点击启动后没有反应吗，如果以前编辑过伪造规则 (Cealing-Host.json) 的话，很有可能是 伪造规则有语法错误 引起的，可以检查一下有没有语法或拼写错误，比如少了或多了逗号之类的

**Comment by Pantyhose-X** [comment]
> 是点击启动后没有反应吗，如果以前编辑过伪造规则 (Cealing-Host.json) 的话，很有可能是 伪造规则有语法错误 引起的，可以检查一下有没有语法或拼写错误，比如少了或多了逗号之类的

谢谢解决了，是伪造规则有语法错误 引起的，开头缩进 我使用了4个空格
