### ISSUE TITLE
可以考虑引入远程hosts-files，实现更多网站的访问

### ISSUE THREAD

**Issue by xfish33** [SpaceTimee/Sheas-Cealer#33]
如题，现在可以访问的网站太少了，可以考虑使用远程hosts-files，实现更多网站的访问，同时还可以屏蔽广告等

**Comment by SpaceTimee** [comment]
远程 hosts-file 是什么东西，现在的 Cealing Host 不就是从远程拉取的吗

**Comment by xfish33** [comment]
远程hosts-files就是远程hosts，可以参见[SwitchHosts](https://github.com/oldj/SwitchHosts)，[googlehosts/hosts](https://github.com/googlehosts/hosts)等项目
现在的Cealing Host 实质上也是一种host，量太少了，很多网站都不能访问，而且都是基于ipv4的，速度比较慢。
成熟的远程hosts文件和Cealing Host基本相同，就是格式不一样，改变一下数据结构，应该就可以使用已有的远程hosts了，不用维护这些数据文件

**Comment by SpaceTimee** [comment]
hosts 其实是一种非常过时的文件格式，而且并不适合用作 Cealing Host 的文件格式

首先 hosts 是一个 域名 ip 的二元映射，而 Cealing Host 是一个 域名 sni ip 三元映射

其次 hosts 不支持通配符，这意味着任何一个稍有不同的子域就得重新写一条规则，即使他们的 ip 完全相同，而且这不仅是多写几条规则的问题，有的网站拥有大量子域，维护者很难找齐所有子域。而 Cealing Host 不仅支持通配符，而且可以做到只要 sni 和 ip 相同，那它就可以写在同一条规则中，这也和大多数审查设备审查时所用的规则相契合

另外 Cealing Host 是 json 格式的文件，这使得 Cealing Host 在程序中远比 hosts 文件容易读取，大多数主流编程语言都已经内置了对 json 格式文件的解析能力，而对 hosts 文件的读取支持的非常少，作为 json 格式文件，Cealing Host 也能支持更多数据类型，比如当一条规则需要拔除整个 sni (而不是将 sni server_name 设置为随机字符或空字符串) 时，Cealing Host 可以将 sni 写成 null，这在 hosts 中无法实现

**Comment by SpaceTimee** [comment]
Cealing Host 中尽可能使用 ipv4 是故意的，Cealing Host 是支持 ipv6，但有很多用户的网络环境不支持，所以我才尽可能在 Cealing Host 中使用 ipv4

**Comment by xfish33** [comment]
可以根据远程hosts，根据一定的规则匹配，转换成Cealing Host 的文件格式，都是规则的文本，转换的难度不会太大，手动维持Cealing Host 的难度确实比较大
感谢作者的付出，能无痛使用Google学术已经很好了
