### ISSUE TITLE
CHOROME 路径里能支持添加自动义参数吗 

### ISSUE THREAD

**Issue by 674273563** [SpaceTimee/Sheas-Cealer#5]
例如 c:\wenjian\gongju\ungoog\chromium.exe --user-data-dir="c:\wenjian\gongju\peizhi"

**Comment by SpaceTimee** [comment]
没做这个功能，不过你可以通过这篇文章的方法手动实现和 Sheas Cealer 相同的效果，然后可以添加自定义参数 -> [《通过配置Chromium系列浏览器启动参数以解决DNS污染与SNI阻断》](https://nicebowl.fun/24_8)

**Comment by SpaceTimee** [comment]
[Sheas Cealer 1.1.1](https://github.com/SpaceTimee/Sheas-Cealer/releases/tag/1.1.1) 现在添加了对额外参数的支持
