### ISSUE TITLE
[功能请求]开机自启动和自动申请管理员权限

### ISSUE THREAD

**Issue by ShuangfanSail** [SpaceTimee/Sheas-Cealer#7]
1.在直接打开的情况下没有管理员权限报错，建议添加自动申请管理员权限
![image](https://github.com/SpaceTimee/Sheas-Cealer/assets/88941547/b8602199-a22a-4218-b5a1-17519e831a40)
2.每次启动浏览器都要重新设置。建议在后台运行并于浏览器启动时自动设置

**Comment by SpaceTimee** [comment]
1. 大多数用户的 UAC 策略并没有这么严格，在较为宽松的 UAC 策略下 Sheas Cealer 是不需要管理员权限的，如果出现拒绝访问，你可以右键然后以管理员身份运行 Sheas Cealer，我希望 Sheas Cealer 仅获取必要的权限等级，来避免提权弹窗干扰用户启动软件时的体验，或让用户对项目的安全性产生不必要担心

2. 我不太清楚你说的设置是指什么的设置，Sheas Cealer 的三项设置 (文件路径，上游链接和额外参数) 都是做了本地记录的，不会因为重新打开软件而消失 (软件更新后倒是有可能需要重新填写)
