### ISSUE TITLE
无法打开外网

### ISSUE THREAD

**Issue by wcwq98** [SpaceTimee/Sheas-Cealer#8]
用完之后咋彻底关闭这个软件，关闭后即使挂代理也无法正常访问网站。删了软件也不得
访问谷歌报错：404. That’s an error.

The requested URL / was not found on this server. That’s all we know.

**Comment by SpaceTimee** [comment]
普通伪造只需要关闭浏览器就可以解除伪造了，全局伪造和全局净化点一下停止全局伪造和停止全局净化就行，如果完全关闭之后还是不能通过正向代理访问谷歌，那就不是 Sheas Cealer 的问题了
