### ISSUE TITLE
[suggestion] 建议修改ui配色

### ISSUE THREAD

**Issue by Yuzhii0718** [SpaceTimee/Sheas-Cealer#9]
这个红色背景配色让人难以看清字体

**Comment by SpaceTimee** [comment]
这样把字体改成白色会好一些吗
![image](https://github.com/user-attachments/assets/8bc54023-bf52-43ad-8f0f-8edf918342db)

**Comment by Yuzhii0718** [comment]
这样确实要更好

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by SpaceTimee** [comment]
1.1.4 版本已修改界面配色并添加了更多对 UI 的自定义功能
https://github.com/SpaceTimee/Sheas-Cealer/releases/tag/1.1.4
